/*
 * This file is generated by jOOQ.
 */
package com.mossonthetree.database;


import com.mossonthetree.database.tables.TBLTrade;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.trade</code>.
     */
    public static final TBLTrade TRADE = TBLTrade.TRADE;
}
