/*
 * This file is generated by jOOQ.
 */
package com.mossonthetree.database;


import com.mossonthetree.database.tables.TBLTrade;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TBLPublic extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final TBLPublic PUBLIC = new TBLPublic();

    /**
     * The table <code>public.trade</code>.
     */
    public final TBLTrade TRADE = TBLTrade.TRADE;

    /**
     * No further instances allowed
     */
    private TBLPublic() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TBLTrade.TRADE
        );
    }
}
