/*
 * This file is generated by jOOQ.
 */
package com.mossonthetree.database;


import com.mossonthetree.database.tables.TBLTrade;
import com.mossonthetree.database.tables.records.TBLTradeRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TBLTradeRecord> TRADE_PKEY = Internal.createUniqueKey(TBLTrade.TRADE, DSL.name("trade_pkey"), new TableField[] { TBLTrade.TRADE.TRADE_ID }, true);
}
